/**
 * Database Type Definitions
 * Auto-generated type definitions that match the Supabase PostgreSQL schema.
 * 
 * In production, these would be generated by `npx supabase gen types typescript`.
 * For now, these are manually defined to match the schema in 001_initial_schema.sql.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type BookingStatusEnum = 'pending' | 'confirmed' | 'scheduled' | 'completed' | 'cancelled';

export interface Database {
  public: {
    Tables: {
      scrap_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon_url: string | null;
          image_url: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          icon_url?: string | null;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          icon_url?: string | null;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      scrap_items: {
        Row: {
          id: string;
          category_id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          unit: string;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          category_id: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          unit?: string;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          category_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          unit?: string;
          is_active?: boolean;
          sort_order?: number;
          updated_at?: string;
        };
      };
      scrap_rates: {
        Row: {
          id: string;
          scrap_item_id: string;
          price_per_unit: number;
          city: string;
          effective_from: string;
          effective_to: string | null;
          is_current: boolean;
          created_at: string;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          scrap_item_id: string;
          price_per_unit: number;
          city?: string;
          effective_from?: string;
          effective_to?: string | null;
          is_current?: boolean;
          created_at?: string;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          scrap_item_id?: string;
          price_per_unit?: number;
          city?: string;
          effective_from?: string;
          effective_to?: string | null;
          is_current?: boolean;
          updated_by?: string | null;
        };
      };
      pickup_slots: {
        Row: {
          id: string;
          start_time: string;
          end_time: string;
          label: string;
          max_bookings_per_day: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          start_time: string;
          end_time: string;
          label: string;
          max_bookings_per_day?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          start_time?: string;
          end_time?: string;
          label?: string;
          max_bookings_per_day?: number;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      bookings: {
        Row: {
          id: string;
          booking_number: string;
          customer_name: string;
          customer_phone: string;
          address_line_1: string;
          address_line_2: string | null;
          city: string;
          state: string;
          pincode: string;
          latitude: number | null;
          longitude: number | null;
          slot_id: string;
          pickup_date: string;
          status: BookingStatusEnum;
          estimated_value: number | null;
          actual_value: number | null;
          weight_total: number | null;
          customer_notes: string | null;
          cancellation_reason: string | null;
          scrap_photo_urls: string | null;
          confirmed_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          booking_number?: string;
          customer_name: string;
          customer_phone: string;
          address_line_1: string;
          address_line_2?: string | null;
          city?: string;
          state?: string;
          pincode: string;
          latitude?: number | null;
          longitude?: number | null;
          slot_id: string;
          pickup_date: string;
          status?: BookingStatusEnum;
          estimated_value?: number | null;
          actual_value?: number | null;
          weight_total?: number | null;
          customer_notes?: string | null;
          cancellation_reason?: string | null;
          scrap_photo_urls?: string | null;
          confirmed_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          booking_number?: string;
          customer_name?: string;
          customer_phone?: string;
          address_line_1?: string;
          address_line_2?: string | null;
          city?: string;
          state?: string;
          pincode?: string;
          latitude?: number | null;
          longitude?: number | null;
          slot_id?: string;
          pickup_date?: string;
          status?: BookingStatusEnum;
          estimated_value?: number | null;
          actual_value?: number | null;
          weight_total?: number | null;
          customer_notes?: string | null;
          cancellation_reason?: string | null;
          scrap_photo_urls?: string | null;
          confirmed_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      booking_items: {
        Row: {
          id: string;
          booking_id: string;
          scrap_item_id: string;
          estimated_weight: number;
          actual_weight: number | null;
          rate_applied: number;
          subtotal: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          scrap_item_id: string;
          estimated_weight: number;
          actual_weight?: number | null;
          rate_applied: number;
          subtotal: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          scrap_item_id?: string;
          estimated_weight?: number;
          actual_weight?: number | null;
          rate_applied?: number;
          subtotal?: number;
        };
      };
      booking_status_logs: {
        Row: {
          id: string;
          booking_id: string;
          previous_status: BookingStatusEnum | null;
          new_status: BookingStatusEnum;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          previous_status?: BookingStatusEnum | null;
          new_status: BookingStatusEnum;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          previous_status?: BookingStatusEnum | null;
          new_status?: BookingStatusEnum;
          notes?: string | null;
        };
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          excerpt: string | null;
          content: string;
          cover_image_url: string | null;
          author_name: string;
          is_published: boolean;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          excerpt?: string | null;
          content: string;
          cover_image_url?: string | null;
          author_name?: string;
          is_published?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          excerpt?: string | null;
          content?: string;
          cover_image_url?: string | null;
          author_name?: string;
          is_published?: boolean;
          published_at?: string | null;
          updated_at?: string;
        };
      };
      contact_submissions: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          subject: string;
          message: string;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string | null;
          subject: string;
          message: string;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          subject?: string;
          message?: string;
          is_read?: boolean;
        };
      };
    };
    Enums: {
      booking_status: BookingStatusEnum;
    };
  };
}

/** Convenience type aliases */
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
