/**
 * Bookings API Route Handler
 * POST /api/bookings — Create a new guest booking
 * GET /api/bookings?phone=XXXXXXXXXX — List bookings by phone
 * GET /api/bookings?number=SW-XXXX-XXX — Get booking by booking number
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/services/supabase/server';
import { z } from 'zod';

/** Validation schema for creating a booking */
const createBookingSchema = z.object({
  customer_name: z.string().min(2, 'Name must be at least 2 characters'),
  customer_phone: z.string().regex(/^(\+91)?[6-9]\d{9}$/, 'Enter a valid Indian phone number'),
  address_line_1: z.string().min(5, 'Address is required'),
  address_line_2: z.string().optional(),
  city: z.string().min(2).default('Bangalore'),
  state: z.string().min(2).default('Karnataka'),
  pincode: z.string().length(6, 'Pincode must be 6 digits'),
  slot_id: z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, 'Invalid slot'),
  pickup_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Invalid date format'),
  customer_notes: z.string().optional(),
  scrap_photo_urls: z.string().optional(),
  items: z
    .array(
      z.object({
        scrap_item_id: z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, 'Invalid scrap item ID'),
        estimated_weight: z.number().positive(),
        rate_applied: z.number().nonnegative(),
      }),
    )
    .min(1, 'At least one item is required'),
});

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const body = await request.json();

    // Validate request body
    const result = createBookingSchema.safeParse(body);
    if (!result.success) {
      return NextResponse.json(
        {
          data: null,
          error: result.error.issues.map((e) => e.message).join(', '),
          success: false,
        },
        { status: 400 },
      );
    }

    const { items, ...bookingData } = result.data;

    // Calculate estimated value
    const estimatedValue = items.reduce(
      (sum, item) => sum + item.estimated_weight * item.rate_applied,
      0,
    );

    // Insert booking (booking_number auto-generated by trigger)
    const { data: booking, error: bookingError } = await supabase
      .from('bookings')
      .insert({
        ...bookingData,
        estimated_value: estimatedValue,
        booking_number: '', // Will be auto-generated by trigger
      })
      .select()
      .single();

    if (bookingError) {
      console.error('Booking insert error:', bookingError);
      return NextResponse.json(
        { data: null, error: 'Failed to create booking', success: false },
        { status: 500 },
      );
    }

    // Insert booking items
    const bookingItems = items.map((item) => ({
      booking_id: booking.id,
      scrap_item_id: item.scrap_item_id,
      estimated_weight: item.estimated_weight,
      rate_applied: item.rate_applied,
      subtotal: item.estimated_weight * item.rate_applied,
    }));

    const { error: itemsError } = await supabase.from('booking_items').insert(bookingItems);

    if (itemsError) {
      console.error('Booking items insert error:', itemsError);
      // Booking was created but items failed — log but don't fail completely
    }

    return NextResponse.json(
      { data: booking, error: null, success: true },
      { status: 201 },
    );
  } catch (err) {
    console.error('Bookings POST error:', err);
    return NextResponse.json(
      { data: null, error: 'Internal server error', success: false },
      { status: 500 },
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { searchParams } = new URL(request.url);
    const phone = searchParams.get('phone');
    const bookingNumber = searchParams.get('number');

    if (!phone && !bookingNumber) {
      return NextResponse.json(
        { data: null, error: 'Provide either phone or number parameter', success: false },
        { status: 400 },
      );
    }

    let query = supabase
      .from('bookings')
      .select(`
        *,
        slot:pickup_slots(id, label, start_time, end_time)
      `)
      .is('deleted_at', null)
      .order('created_at', { ascending: false });

    if (bookingNumber) {
      query = query.eq('booking_number', bookingNumber);
    } else if (phone) {
      // Normalize phone (remove +91 prefix if present)
      const normalizedPhone = phone.replace(/^\+91/, '');
      query = query.or(`customer_phone.eq.${normalizedPhone},customer_phone.eq.+91${normalizedPhone}`);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Bookings fetch error:', error);
      return NextResponse.json(
        { data: null, error: 'Failed to fetch bookings', success: false },
        { status: 500 },
      );
    }

    return NextResponse.json({ data, error: null, success: true });
  } catch (err) {
    console.error('Bookings GET error:', err);
    return NextResponse.json(
      { data: null, error: 'Internal server error', success: false },
      { status: 500 },
    );
  }
}
